import type { Habit } from '../src/types';
import { dayOffset } from './tasks';

/** Returns an array of date strings for the last `count` days (excluding today). */
function lastNDays(count: number): string[] {
  return Array.from({ length: count }, (_, i) => dayOffset(-(i + 1))).reverse();
}

export function getSeedHabits(): Habit[] {
  const today = dayOffset(0);
  const now = new Date().toISOString();

  return [
    {
      id: 'seed-habit-001',
      type: 'habit',
      title: 'Ранкова зарядка',
      description: '15 хвилин розминки одразу після підйому',
      date: today,
      startTime: '07:00',
      endTime: '07:15',
      status: 'pending',
      themeColor: '#FCFFC6',
      priority: 'medium',
      difficulty: 'easy',
      estimatedDuration: 15,
      dueDate: null,
      deadline: null,
      tags: ['здоровʼя'],
      reminder: {
        mode: 'before_start',
        minutesBefore: 5,
        time: null,
        recurrent: true,
        enabled: true,
      },
      linkedGoalId: null,
      voiceNote: null,
      completedAt: null,
      archived: false,
      deletedAt: null,
      createdAt: now,
      updatedAt: now,
      recurrence: { type: 'daily', days: [0, 1, 2, 3, 4, 5, 6] },
      streak: 5,
      bestStreak: 7,
      completionDates: lastNDays(5),
    },
    {
      id: 'seed-habit-002',
      type: 'habit',
      title: 'Читання перед сном',
      description: 'Мінімум 20 сторінок художньої або нон-фікшн літератури',
      date: today,
      startTime: '22:00',
      endTime: '22:30',
      status: 'pending',
      themeColor: '#FFD9D9',
      priority: 'low',
      difficulty: 'easy',
      estimatedDuration: 30,
      dueDate: null,
      deadline: null,
      tags: ['навчання', 'особисте'],
      reminder: {
        mode: 'at_time',
        minutesBefore: 0,
        time: '22:00',
        recurrent: true,
        enabled: true,
      },
      linkedGoalId: 'seed-goal-001',
      voiceNote: null,
      completedAt: null,
      archived: false,
      deletedAt: null,
      createdAt: now,
      updatedAt: now,
      recurrence: { type: 'daily', days: [0, 1, 2, 3, 4, 5, 6] },
      streak: 3,
      bestStreak: 12,
      completionDates: lastNDays(3),
    },
    {
      id: 'seed-habit-003',
      type: 'habit',
      title: 'Медитація',
      description: '10 хвилин усвідомленого дихання',
      date: today,
      startTime: '08:00',
      endTime: '08:10',
      status: 'pending',
      themeColor: '#FCFFC6',
      priority: 'medium',
      difficulty: 'medium',
      estimatedDuration: 10,
      dueDate: null,
      deadline: null,
      tags: ['здоровʼя'],
      reminder: {
        mode: 'before_start',
        minutesBefore: 5,
        time: null,
        recurrent: true,
        enabled: false,
      },
      linkedGoalId: null,
      voiceNote: null,
      completedAt: null,
      archived: false,
      deletedAt: null,
      createdAt: now,
      updatedAt: now,
      // Mon=1, Wed=3, Fri=5
      recurrence: { type: 'weekly', days: [1, 3, 5] },
      streak: 2,
      bestStreak: 4,
      completionDates: lastNDays(2),
    },
  ];
}
