import type { Task } from '../src/types';

// ─── Helpers ──────────────────────────────────────────────────────────────────

/** Returns 'YYYY-MM-DD' for today + n days (negative = past). */
export function dayOffset(n: number): string {
  // Seed data must align with app's calendar logic (Kyiv timezone).
  // Otherwise tasks can "shift" a day and not appear on the selected date.
  const KYIV_TZ = 'Europe/Kyiv';
  const base = new Date();
  base.setDate(base.getDate() + n);

  const parts = new Intl.DateTimeFormat('en-CA', {
    timeZone: KYIV_TZ,
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
  }).formatToParts(base);

  const year = parts.find((p) => p.type === 'year')?.value ?? '1970';
  const month = parts.find((p) => p.type === 'month')?.value ?? '01';
  const day = parts.find((p) => p.type === 'day')?.value ?? '01';

  return `${year}-${month}-${day}`;
}

/** Returns an ISO datetime string for a given date offset at a specific time. */
function isoAt(dayN: number, time: string): string {
  const date = dayOffset(dayN);
  return `${date}T${time}:00.000Z`;
}

const noReminder = {
  mode: 'before_start' as const,
  minutesBefore: 10,
  time: null,
  recurrent: false,
  enabled: false,
};

const withReminder = {
  mode: 'before_start' as const,
  minutesBefore: 15,
  time: null,
  recurrent: false,
  enabled: true,
};

// ─── Seed tasks ───────────────────────────────────────────────────────────────

export function getSeedTasks(): Task[] {
  return [
    // ── today−3: 3 completed, 1 skipped ──────────────────────────────────────
    {
      id: 'seed-task-001',
      type: 'task',
      title: 'Ранковий дзвінок з командою',
      description: 'Синхронізація по поточному спринту',
      date: dayOffset(-3),
      startTime: '09:00',
      endTime: '10:00',
      status: 'completed',
      themeColor: '#FCFFC6',
      priority: 'high',
      difficulty: 'easy',
      estimatedDuration: 60,
      dueDate: null,
      deadline: null,
      tags: ['робота'],
      reminder: noReminder,
      linkedGoalId: null,
      voiceNote: null,
      completedAt: isoAt(-3, '10:00'),
      archived: false,
      deletedAt: null,
      createdAt: isoAt(-3, '08:30'),
      updatedAt: isoAt(-3, '10:00'),
    },
    {
      id: 'seed-task-002',
      type: 'task',
      title: 'Підготовка презентації',
      description: 'Слайди для демо в кінці тижня',
      date: dayOffset(-3),
      startTime: '11:00',
      endTime: '12:00',
      status: 'completed',
      themeColor: '#FCFFC6',
      priority: 'high',
      difficulty: 'medium',
      estimatedDuration: 60,
      dueDate: null,
      deadline: null,
      tags: ['робота', 'навчання'],
      reminder: noReminder,
      linkedGoalId: null,
      voiceNote: null,
      completedAt: isoAt(-3, '12:05'),
      archived: false,
      deletedAt: null,
      createdAt: isoAt(-3, '08:30'),
      updatedAt: isoAt(-3, '12:05'),
    },
    {
      id: 'seed-task-003',
      type: 'task',
      title: 'Тренування в залі',
      description: '',
      date: dayOffset(-3),
      startTime: '14:00',
      endTime: '15:30',
      status: 'completed',
      themeColor: '#FCFFC6',
      priority: 'medium',
      difficulty: 'hard',
      estimatedDuration: 90,
      dueDate: null,
      deadline: null,
      tags: ['здоровʼя'],
      reminder: noReminder,
      linkedGoalId: 'seed-goal-002',
      voiceNote: null,
      completedAt: isoAt(-3, '15:35'),
      archived: false,
      deletedAt: null,
      createdAt: isoAt(-3, '08:30'),
      updatedAt: isoAt(-3, '15:35'),
    },
    {
      id: 'seed-task-004',
      type: 'task',
      title: 'Прогулянка з другом',
      description: 'Парк біля будинку',
      date: dayOffset(-3),
      startTime: '18:00',
      endTime: '19:00',
      status: 'skipped',
      themeColor: '#FCFFC6',
      priority: 'low',
      difficulty: 'easy',
      estimatedDuration: 60,
      dueDate: null,
      deadline: null,
      tags: ['особисте'],
      reminder: noReminder,
      linkedGoalId: null,
      voiceNote: null,
      completedAt: null,
      archived: false,
      deletedAt: null,
      createdAt: isoAt(-3, '08:30'),
      updatedAt: isoAt(-3, '08:30'),
    },

    // ── today−2: 2 completed, 1 skipped, 1 pending ───────────────────────────
    {
      id: 'seed-task-005',
      type: 'task',
      title: 'Медитація та ранкове читання',
      description: '20 хв медитації + 40 хв книга',
      date: dayOffset(-2),
      startTime: '08:30',
      endTime: '09:30',
      status: 'completed',
      themeColor: '#FFD9D9',
      priority: 'low',
      difficulty: 'easy',
      estimatedDuration: 60,
      dueDate: null,
      deadline: null,
      tags: ['здоровʼя', 'особисте'],
      reminder: noReminder,
      linkedGoalId: 'seed-goal-001',
      voiceNote: null,
      completedAt: isoAt(-2, '09:32'),
      archived: false,
      deletedAt: null,
      createdAt: isoAt(-2, '08:00'),
      updatedAt: isoAt(-2, '09:32'),
    },
    {
      id: 'seed-task-006',
      type: 'task',
      title: 'Розробка нового функціоналу',
      description: 'Компонент форми реєстрації',
      date: dayOffset(-2),
      startTime: '10:00',
      endTime: '12:00',
      status: 'completed',
      themeColor: '#FCFFC6',
      priority: 'high',
      difficulty: 'hard',
      estimatedDuration: 120,
      dueDate: null,
      deadline: null,
      tags: ['робота'],
      reminder: noReminder,
      linkedGoalId: null,
      voiceNote: null,
      completedAt: isoAt(-2, '12:10'),
      archived: false,
      deletedAt: null,
      createdAt: isoAt(-2, '08:00'),
      updatedAt: isoAt(-2, '12:10'),
    },
    {
      id: 'seed-task-007',
      type: 'task',
      title: 'Обід з колегою',
      description: '',
      date: dayOffset(-2),
      startTime: '13:00',
      endTime: '13:30',
      status: 'skipped',
      themeColor: '#FFD9D9',
      priority: 'low',
      difficulty: 'easy',
      estimatedDuration: 30,
      dueDate: null,
      deadline: null,
      tags: ['особисте'],
      reminder: noReminder,
      linkedGoalId: null,
      voiceNote: null,
      completedAt: null,
      archived: false,
      deletedAt: null,
      createdAt: isoAt(-2, '08:00'),
      updatedAt: isoAt(-2, '08:00'),
    },
    {
      id: 'seed-task-008',
      type: 'task',
      title: 'Перевірка пошти та відповіді',
      description: '',
      date: dayOffset(-2),
      startTime: '16:00',
      endTime: '17:00',
      status: 'pending',
      themeColor: '#FCFFC6',
      priority: 'medium',
      difficulty: 'easy',
      estimatedDuration: 60,
      dueDate: null,
      deadline: null,
      tags: ['робота'],
      reminder: noReminder,
      linkedGoalId: null,
      voiceNote: null,
      completedAt: null,
      archived: false,
      deletedAt: null,
      createdAt: isoAt(-2, '08:00'),
      updatedAt: isoAt(-2, '08:00'),
    },

    // ── today−1: 2 completed, 2 pending ──────────────────────────────────────
    {
      id: 'seed-task-009',
      type: 'task',
      title: 'Стенд-ап та планування спринту',
      description: '',
      date: dayOffset(-1),
      startTime: '09:00',
      endTime: '10:30',
      status: 'completed',
      themeColor: '#FCFFC6',
      priority: 'high',
      difficulty: 'medium',
      estimatedDuration: 90,
      dueDate: null,
      deadline: null,
      tags: ['робота'],
      reminder: noReminder,
      linkedGoalId: null,
      voiceNote: null,
      completedAt: isoAt(-1, '10:35'),
      archived: false,
      deletedAt: null,
      createdAt: isoAt(-1, '08:30'),
      updatedAt: isoAt(-1, '10:35'),
    },
    {
      id: 'seed-task-010',
      type: 'task',
      title: 'Вивчення нового матеріалу',
      description: 'TypeScript generics та utility types',
      date: dayOffset(-1),
      startTime: '12:00',
      endTime: '13:00',
      status: 'completed',
      themeColor: '#FFD9D9',
      priority: 'medium',
      difficulty: 'medium',
      estimatedDuration: 60,
      dueDate: null,
      deadline: null,
      tags: ['навчання'],
      reminder: noReminder,
      linkedGoalId: 'seed-goal-001',
      voiceNote: null,
      completedAt: isoAt(-1, '13:05'),
      archived: false,
      deletedAt: null,
      createdAt: isoAt(-1, '08:30'),
      updatedAt: isoAt(-1, '13:05'),
    },
    {
      id: 'seed-task-011',
      type: 'task',
      title: 'Написання звіту',
      description: 'Щотижневий звіт по задачах',
      date: dayOffset(-1),
      startTime: '15:00',
      endTime: '16:00',
      status: 'pending',
      themeColor: '#FCFFC6',
      priority: 'medium',
      difficulty: 'medium',
      estimatedDuration: 60,
      dueDate: null,
      deadline: null,
      tags: ['робота'],
      reminder: noReminder,
      linkedGoalId: null,
      voiceNote: null,
      completedAt: null,
      archived: false,
      deletedAt: null,
      createdAt: isoAt(-1, '08:30'),
      updatedAt: isoAt(-1, '08:30'),
    },
    {
      id: 'seed-task-012',
      type: 'task',
      title: 'Готування вечері',
      description: '',
      date: dayOffset(-1),
      startTime: '19:00',
      endTime: '20:00',
      status: 'pending',
      themeColor: '#FCFFC6',
      priority: 'low',
      difficulty: 'easy',
      estimatedDuration: 60,
      dueDate: null,
      deadline: null,
      tags: ['дім'],
      reminder: noReminder,
      linkedGoalId: null,
      voiceNote: null,
      completedAt: null,
      archived: false,
      deletedAt: null,
      createdAt: isoAt(-1, '08:30'),
      updatedAt: isoAt(-1, '08:30'),
    },

    // ── today: all pending, tasks 13 & 14 intentionally overlap ───────────────
    {
      id: 'seed-task-013',
      type: 'task',
      title: 'Робочий мітинг',
      description: 'Огляд цілей на тиждень',
      date: dayOffset(0),
      startTime: '09:00',
      endTime: '10:00',
      status: 'pending',
      themeColor: '#FCFFC6',
      priority: 'high',
      difficulty: 'easy',
      estimatedDuration: 60,
      dueDate: null,
      deadline: null,
      tags: ['робота'],
      reminder: withReminder,
      linkedGoalId: null,
      voiceNote: null,
      completedAt: null,
      archived: false,
      deletedAt: null,
      createdAt: isoAt(0, '07:00'),
      updatedAt: isoAt(0, '07:00'),
    },
    {
      id: 'seed-task-014',
      type: 'task',
      title: 'Огляд коду (перетин!)',
      description: 'Перетинається з мітингом — для тестування timeline',
      date: dayOffset(0),
      startTime: '09:30',
      endTime: '10:30',
      status: 'pending',
      themeColor: '#FFD9D9',
      priority: 'high',
      difficulty: 'medium',
      estimatedDuration: 60,
      dueDate: null,
      deadline: null,
      tags: ['робота'],
      reminder: noReminder,
      linkedGoalId: null,
      voiceNote: null,
      completedAt: null,
      archived: false,
      deletedAt: null,
      createdAt: isoAt(0, '07:00'),
      updatedAt: isoAt(0, '07:00'),
    },
    {
      id: 'seed-task-015',
      type: 'task',
      title: 'Похід до магазину',
      description: 'Продукти на тиждень',
      date: dayOffset(0),
      startTime: '12:00',
      endTime: '13:00',
      status: 'pending',
      themeColor: '#FCFFC6',
      priority: 'low',
      difficulty: 'easy',
      estimatedDuration: 60,
      dueDate: null,
      deadline: null,
      tags: ['дім'],
      reminder: noReminder,
      linkedGoalId: null,
      voiceNote: null,
      completedAt: null,
      archived: false,
      deletedAt: null,
      createdAt: isoAt(0, '07:00'),
      updatedAt: isoAt(0, '07:00'),
    },
    {
      id: 'seed-task-016',
      type: 'task',
      title: 'Спорт',
      description: 'Кардіо 30 хв + силові вправи',
      date: dayOffset(0),
      startTime: '15:00',
      endTime: '16:30',
      status: 'pending',
      themeColor: '#FCFFC6',
      priority: 'medium',
      difficulty: 'hard',
      estimatedDuration: 90,
      dueDate: null,
      deadline: null,
      tags: ['здоровʼя'],
      reminder: withReminder,
      linkedGoalId: 'seed-goal-002',
      voiceNote: null,
      completedAt: null,
      archived: false,
      deletedAt: null,
      createdAt: isoAt(0, '07:00'),
      updatedAt: isoAt(0, '07:00'),
    },

    // ── today+1: all pending ──────────────────────────────────────────────────
    {
      id: 'seed-task-017',
      type: 'task',
      title: 'Дзвінок з клієнтом',
      description: 'Обговорення вимог до нової фічі',
      date: dayOffset(1),
      startTime: '10:00',
      endTime: '11:00',
      status: 'pending',
      themeColor: '#FCFFC6',
      priority: 'high',
      difficulty: 'medium',
      estimatedDuration: 60,
      dueDate: null,
      deadline: null,
      tags: ['робота'],
      reminder: withReminder,
      linkedGoalId: null,
      voiceNote: null,
      completedAt: null,
      archived: false,
      deletedAt: null,
      createdAt: isoAt(1, '08:00'),
      updatedAt: isoAt(1, '08:00'),
    },
    {
      id: 'seed-task-018',
      type: 'task',
      title: 'Читання книги',
      description: 'Atomic Habits — глава 7',
      date: dayOffset(1),
      startTime: '13:00',
      endTime: '14:00',
      status: 'pending',
      themeColor: '#FFD9D9',
      priority: 'low',
      difficulty: 'easy',
      estimatedDuration: 60,
      dueDate: null,
      deadline: null,
      tags: ['навчання', 'особисте'],
      reminder: noReminder,
      linkedGoalId: 'seed-goal-001',
      voiceNote: null,
      completedAt: null,
      archived: false,
      deletedAt: null,
      createdAt: isoAt(1, '08:00'),
      updatedAt: isoAt(1, '08:00'),
    },
    {
      id: 'seed-task-019',
      type: 'task',
      title: 'Тренування',
      description: 'Пробіжка 5 км',
      date: dayOffset(1),
      startTime: '17:00',
      endTime: '18:30',
      status: 'pending',
      themeColor: '#FCFFC6',
      priority: 'medium',
      difficulty: 'medium',
      estimatedDuration: 90,
      dueDate: null,
      deadline: null,
      tags: ['здоровʼя'],
      reminder: withReminder,
      linkedGoalId: 'seed-goal-002',
      voiceNote: null,
      completedAt: null,
      archived: false,
      deletedAt: null,
      createdAt: isoAt(1, '08:00'),
      updatedAt: isoAt(1, '08:00'),
    },

    // ── today+2: all pending ──────────────────────────────────────────────────
    {
      id: 'seed-task-020',
      type: 'task',
      title: 'Планування тижня',
      description: 'Розподіл задач та пріоритетів',
      date: dayOffset(2),
      startTime: '09:00',
      endTime: '10:00',
      status: 'pending',
      themeColor: '#FCFFC6',
      priority: 'medium',
      difficulty: 'easy',
      estimatedDuration: 60,
      dueDate: null,
      deadline: null,
      tags: ['робота'],
      reminder: noReminder,
      linkedGoalId: null,
      voiceNote: null,
      completedAt: null,
      archived: false,
      deletedAt: null,
      createdAt: isoAt(2, '08:00'),
      updatedAt: isoAt(2, '08:00'),
    },
    {
      id: 'seed-task-021',
      type: 'task',
      title: 'Проект: дизайн макету',
      description: 'Wireframe для нового екрана налаштувань',
      date: dayOffset(2),
      startTime: '11:00',
      endTime: '12:30',
      status: 'pending',
      themeColor: '#FCFFC6',
      priority: 'high',
      difficulty: 'hard',
      estimatedDuration: 90,
      dueDate: null,
      deadline: null,
      tags: ['робота', 'навчання'],
      reminder: noReminder,
      linkedGoalId: null,
      voiceNote: null,
      completedAt: null,
      archived: false,
      deletedAt: null,
      createdAt: isoAt(2, '08:00'),
      updatedAt: isoAt(2, '08:00'),
    },
    {
      id: 'seed-task-022',
      type: 'task',
      title: 'Зустріч з другом',
      description: 'Кавʼярня о 16:00',
      date: dayOffset(2),
      startTime: '16:00',
      endTime: '17:00',
      status: 'pending',
      themeColor: '#FCFFC6',
      priority: 'low',
      difficulty: 'easy',
      estimatedDuration: 60,
      dueDate: null,
      deadline: null,
      tags: ['особисте'],
      reminder: withReminder,
      linkedGoalId: null,
      voiceNote: null,
      completedAt: null,
      archived: false,
      deletedAt: null,
      createdAt: isoAt(2, '08:00'),
      updatedAt: isoAt(2, '08:00'),
    },

    // ── today+3: all pending, reminders enabled ───────────────────────────────
    {
      id: 'seed-task-023',
      type: 'task',
      title: 'Ранкова пробіжка',
      description: '5 км по парку',
      date: dayOffset(3),
      startTime: '08:00',
      endTime: '09:00',
      status: 'pending',
      themeColor: '#FCFFC6',
      priority: 'medium',
      difficulty: 'medium',
      estimatedDuration: 60,
      dueDate: null,
      deadline: null,
      tags: ['здоровʼя'],
      reminder: withReminder,
      linkedGoalId: 'seed-goal-002',
      voiceNote: null,
      completedAt: null,
      archived: false,
      deletedAt: null,
      createdAt: isoAt(3, '07:00'),
      updatedAt: isoAt(3, '07:00'),
    },
    {
      id: 'seed-task-024',
      type: 'task',
      title: 'Медична консультація',
      description: 'Запис до лікаря о 14:00',
      date: dayOffset(3),
      startTime: '14:00',
      endTime: '15:30',
      status: 'pending',
      themeColor: '#FFD9D9',
      priority: 'high',
      difficulty: 'easy',
      estimatedDuration: 90,
      dueDate: null,
      deadline: null,
      tags: ['здоровʼя'],
      reminder: withReminder,
      linkedGoalId: null,
      voiceNote: null,
      completedAt: null,
      archived: false,
      deletedAt: null,
      createdAt: isoAt(3, '07:00'),
      updatedAt: isoAt(3, '07:00'),
    },
    {
      id: 'seed-task-025',
      type: 'task',
      title: 'Сімейна вечеря',
      description: '',
      date: dayOffset(3),
      startTime: '18:00',
      endTime: '19:00',
      status: 'pending',
      themeColor: '#FFD9D9',
      priority: 'low',
      difficulty: 'easy',
      estimatedDuration: 60,
      dueDate: null,
      deadline: null,
      tags: ['особисте'],
      reminder: noReminder,
      linkedGoalId: null,
      voiceNote: null,
      completedAt: null,
      archived: false,
      deletedAt: null,
      createdAt: isoAt(3, '07:00'),
      updatedAt: isoAt(3, '07:00'),
    },

    // ── today: anytime tasks (no startTime, no endTime) ──────────────────────
    {
      id: 'seed-task-anytime-001',
      type: 'task',
      title: 'Відповісти на листи',
      description: '',
      date: dayOffset(0),
      startDate: null,
      endDate: null,
      startTime: null,
      endTime: null,
      status: 'pending',
      themeColor: '#FCFFC6',
      priority: 'medium',
      difficulty: 'easy',
      estimatedDuration: null,
      dueDate: null,
      deadline: null,
      tags: ['робота'],
      reminder: noReminder,
      linkedGoalId: null,
      voiceNote: null,
      completedAt: null,
      isInbox: false,
      sortIndex: null,
      archived: false,
      deletedAt: null,
      createdAt: isoAt(0, '07:00'),
      updatedAt: isoAt(0, '07:00'),
    },
    {
      id: 'seed-task-anytime-002',
      type: 'task',
      title: 'Замовити продукти онлайн',
      description: '',
      date: dayOffset(0),
      startDate: null,
      endDate: null,
      startTime: null,
      endTime: null,
      status: 'completed',
      themeColor: '#FCFFC6',
      priority: 'low',
      difficulty: 'easy',
      estimatedDuration: null,
      dueDate: null,
      deadline: null,
      tags: ['дім'],
      reminder: noReminder,
      linkedGoalId: null,
      voiceNote: null,
      completedAt: isoAt(0, '09:15'),
      isInbox: false,
      sortIndex: null,
      archived: false,
      deletedAt: null,
      createdAt: isoAt(0, '07:00'),
      updatedAt: isoAt(0, '09:15'),
    },

    // ── today: flexible tasks (no startTime, has endTime) ─────────────────────
    {
      id: 'seed-task-flex-001',
      type: 'task',
      title: 'Зателефонувати лікарю',
      description: 'Записатись на прийом',
      date: dayOffset(0),
      startDate: null,
      endDate: null,
      startTime: null,
      endTime: '12:00',
      status: 'pending',
      themeColor: '#FCFFC6',
      priority: 'medium',
      difficulty: 'easy',
      estimatedDuration: 10,
      dueDate: null,
      deadline: null,
      tags: ['здоровʼя'],
      reminder: noReminder,
      linkedGoalId: null,
      voiceNote: null,
      completedAt: null,
      isInbox: false,
      sortIndex: null,
      archived: false,
      deletedAt: null,
      createdAt: isoAt(0, '07:00'),
      updatedAt: isoAt(0, '07:00'),
    },
    {
      id: 'seed-task-flex-002',
      type: 'task',
      title: 'Оплатити комунальні',
      description: 'Електрика та вода за минулий місяць',
      date: dayOffset(0),
      startDate: null,
      endDate: null,
      startTime: null,
      endTime: '18:00',
      status: 'pending',
      themeColor: '#FCFFC6',
      priority: 'high',
      difficulty: 'easy',
      estimatedDuration: 15,
      dueDate: null,
      deadline: null,
      tags: ['дім'],
      reminder: noReminder,
      linkedGoalId: null,
      voiceNote: null,
      completedAt: null,
      isInbox: false,
      sortIndex: null,
      archived: false,
      deletedAt: null,
      createdAt: isoAt(0, '07:00'),
      updatedAt: isoAt(0, '07:00'),
    },
    {
      id: 'seed-task-flex-003',
      type: 'task',
      title: 'Прочитати главу книги',
      description: '"Атомні звички" — глава 5',
      date: dayOffset(0),
      startDate: null,
      endDate: null,
      startTime: null,
      endTime: '22:00',
      status: 'pending',
      themeColor: '#FCFFC6',
      priority: 'low',
      difficulty: 'easy',
      estimatedDuration: 30,
      dueDate: null,
      deadline: null,
      tags: ['навчання'],
      reminder: noReminder,
      linkedGoalId: null,
      voiceNote: null,
      completedAt: null,
      isInbox: false,
      sortIndex: null,
      archived: false,
      deletedAt: null,
      createdAt: isoAt(0, '07:00'),
      updatedAt: isoAt(0, '07:00'),
    },
  ];
}
